import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

//import Link from "next/link";

const WWSS_TOKEN = "tt-61e807";
const WWSS_ACCOUNT = "westwingstudio.surveysparrow.com";
const WWSS_SURVEY_NAME = "dein-eigenes-projekt";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <style jsx>{`
          .section {
            background-color: aquamarine;
            padding: 50px 100px;
            min-height: 300px;
          }
        `}</style>
        <div className="section">Section 1</div>
        <div className="section">Section 2</div>
        <div className="section">Section 3</div>
        <div id="sparrow-block" style={{height: '100vh'}}>
          <script
            dangerouslySetInnerHTML={{
              __html: `
                window.SS_WIDGET_TOKEN = ${JSON.stringify(WWSS_TOKEN)};
                window.SS_ACCOUNT = ${JSON.stringify(WWSS_ACCOUNT)};
                window.SS_SURVEY_NAME = ${JSON.stringify(WWSS_SURVEY_NAME)};
                function Sparrow(){Sparrow.update.apply(Sparrow,arguments)}
                Sparrow.args=[];
                Sparrow.update=function(){for(var r=arguments.length,a=new Array(r),p=0;p<r;p++)a[p]=arguments[p];Sparrow.args.push(a)};
                window.SparrowLauncher=Sparrow;`,
            }}
          />
          <script
            type="text/javascript"
            id="ss-widget"
            defer
            src={`//${WWSS_ACCOUNT}/widget/${WWSS_TOKEN}`}
          />
        </div>
        <div className="section">Section 4</div>
        <div className="section">Section 5</div>
        <div className="section">Section 5</div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
